version: '3'
services:
  db:
    environment:
      - POSTGRES_PASSWORD=test1234
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    environment:
      - RAILS_ENV=docker_test
      - RAILS_MASTER_KEY=63654e5052a8113c5c659ea60c7e0cb8
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
