default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: api_scienti
  password: postgres

test:
  <<: *default
  host: localhost
  database: api_scienti_test
  password: postgres

docker_test:
  <<: *default
  host: db
  database: api_scienti_docker
  password: test1234
  